apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/devops_user/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sun, 07 Dec 2025 14:53:26 EST
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sun, 07 Dec 2025 14:53:26 EST
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
users:
- name: minikube
  user:
    client-certificate: /home/devops_user/.minikube/profiles/minikube/client.crt
    client-key: /home/devops_user/.minikube/profiles/minikube/client.key
