apiVersion: apps/v1
kind: Deployment
metadata:
  name: poster-ui-deployment
  labels:
    app: poster-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poster-ui
  template:
    metadata:
      labels:
        app: poster-ui
    spec:
      containers:
        - name: poster-ui-container
          image: vitar04/poster-ui:42fe971244238aed41ef0908cfde86727d9d7afc
          ports:
            - containerPort: 3000
